apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: kustomize-

resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml

imageTags:
  - name: gcr.io/heptio-images/ks-guestbook-demo
    newTag: "0.2"
